name: Deploy Kubernetes Cluster

on:
  workflow_dispatch: # Execução manual sob demanda

jobs:
  deploy:
    runs-on: self-hosted # Roda no seu runner local na VM 192.168.122.22
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Rodar Playbook de Provisionamento e Inicialização do Cluster
        run: |
          ansible-playbook playbooks/site.yml
