name: Deploy Kubernetes Cluster

on:
  workflow_dispatch:   # execução manual
  # push:
  #   branches: [ main ]
  #   paths:
  #     - 'ansible/**'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key (opcional, se usar SSH)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 192.168.0.40 >> ~/.ssh/known_hosts

      - name: Run Ansible playbook with sudo
        env:
          ANSIBLE_BECOME_PASS: ${{ secrets.SUDO_PASSWORD }}
        run: |
          ansible-playbook ansible/k8s-cluster-prep.yml \
            -i ansible/inventory.ini \
            --extra-vars "ansible_become_pass=$ANSIBLE_BECOME_PASS"
