name: Cluster Health Check

on:
  workflow_dispatch: # Permite o disparo manual pelo botão no GitHub
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["Deploy Kubernetes Cluster"]
    types:
      - completed

jobs:
  health:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check nodes via SSH
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no root@192.168.0.40 "kubectl get nodes -o wide"
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no root@192.168.0.40 "kubectl get pods -n kube-system"

      - name: Check GPU availability via SSH
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no root@192.168.0.40 "kubectl get nodes -o json | jq '.items[] | {name:.metadata.name, gpu:.status.allocatable.\"nvidia.com/gpu\"}'"
